
spring:
  config:
    activate:
      on-profile: "qa"




build:
  version: "2.0"
# Configuration Properties approach
cards:
  message: "Welcome to Bank cards related QA  APIs"
  contactDetails:
    name: "suchank-ojha"
    email: "suchank@gmail.com"
  onCallSupport:
    -(777)255-1000
    -(777)321-2345
